stages:
- smoke
- precache
- lint
- test
language: node_js
node_js: '9'
addons:
  apt:
    packages:
    - libnotify-bin
install: true
before_script: npm install -g npm@5.8.0
before_install: |
  [[ ! -x ~/npm/node_modules/.bin/npm ]] && {
    # caching feature creates `~/npm` for us
    cd ~/npm && npm install npm
    cd -
  } || true
  # avoids bugs around https://github.com/travis-ci/travis-ci/issues/5092
  export PATH=~/npm/node_modules/.bin:$PATH
cache:
  directories:
  - "~/.npm"
jobs:
  include:
  - stage: test
    install: &1
    - npm install -g mocha-webpack
    - npm install
    script: npm run test
    before_install: true
    after_success: npm run coverage
    cache: &2
      directories:
      - "~/.npm"
      - node_modules
  - stage: test
    install: *1
    script: npm run test
    before_install: true
    after_success: npm run coverage
    cache: *2
    node_js: '8'
  - stage: test
    install: *1
    script: npm run test
    before_install: true
    after_success: npm run coverage
    cache: *2
    node_js: '10'
  - stage: lint
    before_install: true
    install:
    - npm install -g standard
    - npm install -g snazzy
    script: npm run lint
  - stage: smoke
    env: 
    before_install: true
    install: &3
    - npm install -g mocha
    - npm install --production --no-shrinkwrap
    script: mocha --no-config --reporter spec test/sanity/sanity.spec.js
    cache: &4
      directories:
      - "~/.npm"
      - node_modules
  - stage: smoke
    env: 
    before_install: true
    install: *3
    script: mocha --no-config --reporter spec test/sanity/sanity.spec.js
    cache: *4
    node_js: '10'
  - stage: smoke
    env: 
    before_install: true
    install: *3
    script: mocha --no-config --reporter spec test/sanity/sanity.spec.js
    cache: *4
    node_js: '8'
  - stage: precache
    script: true
after_success: npm run coverage
services: mongodb
sudo: false
before_deploy:
- rm -rf node_modules
deploy:
  provider: heroku
  api_key:
    secure: KL6xG6pcxhW14Jsc0ATp+iRp0JCjfCJB2ZhLP8n57jK+G9ooEE+YMm8ongI3sFJb+tXbwIb0ye9NbOIR/iNlt9xCwmDs02+LILlBmUU+JvLcL9ImJT6GTu3nLbqsq4QDfuAGAcvWOYa5YRmmITEymf8c8zt9infWbBHhEkxe82OkNKvFlxPvueHD6KlCCmMjm4ygod8ME85OldbUE/R3QeGGZgGV/UlEZjD0CKBIo2/6GF3PnTl5sOoAqpx38I3gX8mc8uLngy2oUVEr4mPIz7lviRisLwk0xKQvLh5gUtLCFOLBwYLbUJf+0jtVyZ8Rv3VDCFPaS+KOQzfqMFpBag9rqCqv3ZFKfaL28xv245cpsMsF4b2W0767EFV7XmWcmDKkKEtNVi6QVZiflr0LaKbvQhgs/S8St5r8Xe46m5vy0ht3EI3KtMAn8cIMSOKctWfExucyK4t1YaQiB7vWZr/OJb+v14le9bvPgki42mRP3RNWWI15C/XZ9tvmrJBVGw9yRTZjzByL6ggHk/GpFy+tiP9mCrol7P5wtTu5COVSfcEVVpajn069dPzkhbZbqoWc67LodOht3JWKg9j30i39ifVIT5SE1ae74Pa0DqHlhPR2T1hon4Q3QhDOKxMT6ooK96hb26jFXyUbMrf1NZyc1a6+8jzQmwdhREYJJWE=
  app: graphql-ec
  skip_cleanup: true
notifications:
  webhooks: https://hooks.slack.com/services/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
